#ifndef MOTORS_H
#define MOTORS_H

#include <Arduino.h>
#include <Motor.h>
#include <types.h>

#define NUMBER_OF_MOTORS (3)

/* MOTOR_ARM DEFINES */
#define MOTOR_ARM_NAME "MOTOR_ARM"
#define MOTOR_ARM_PIN_1_DIRECTION_CONTORLLING (23)
#define MOTOR_ARM_PIN_2_DIRECTION_CONTORLLING (22)
#define MOTOR_ARM_PIN_SPEED_CONTROLLING (21)

#define MOTOR_ARM_SPEED_PWM_CHANNEL_NUMBER (0) // from 0 to 7
#define MOTOR_ARM_SPEED_PWM_CHANNEL_FREQUENCY (5000)
#define MOTOR_ARM_SPEED_PWM_CHANNEL_RESOLUTION (8)

/* MOTOR_TROLLEY DEFINES */
#define MOTOR_TROLLEY_NAME "MOTOR_TROLLEY"
#define MOTOR_TROLLEY_PIN_1_DIRECTION_CONTORLLING (19)
#define MOTOR_TROLLEY_PIN_2_DIRECTION_CONTORLLING (18)
#define MOTOR_TROLLEY_PIN_SPEED_CONTROLLING (17)

#define MOTOR_TROLLEY_SPEED_PWM_CHANNEL_NUMBER (1) // from 0 to 7
#define MOTOR_TROLLEY_SPEED_PWM_CHANNEL_FREQUENCY (5000)
#define MOTOR_TROLLEY_SPEED_PWM_CHANNEL_RESOLUTION (8)

/* MOTOR_COIL DEFINES */
#define MOTOR_COIL_NAME "MOTOR_COIL"
#define MOTOR_COIL_PIN_1_DIRECTION_CONTORLLING (16)
#define MOTOR_COIL_PIN_2_DIRECTION_CONTORLLING (15)
#define MOTOR_COIL_PIN_SPEED_CONTROLLING (14)

#define MOTOR_COIL_SPEED_PWM_CHANNEL_NUMBER (2) // from 0 to 7
#define MOTOR_COIL_SPEED_PWM_CHANNEL_FREQUENCY (5000)
#define MOTOR_COIL_SPEED_PWM_CHANNEL_RESOLUTION (8)

class Motor;

extern Motor* motors[NUMBER_OF_MOTORS];

#endif /* MOTORS_H */