#include <Motors.h>
#include <eepromHandler.h>

static Motor __Motor_arm(
    MOTOR_ARM_NAME,
    MOTOR_ARM_PIN_1_DIRECTION_CONTORLLING,
    MOTOR_ARM_PIN_2_DIRECTION_CONTORLLING,
    MOTOR_ARM_PIN_SPEED_CONTROLLING,
    MOTOR_ARM_SPEED_PWM_CHANNEL_NUMBER,
    MOTOR_ARM_SPEED_PWM_CHANNEL_FREQUENCY, 
    MOTOR_ARM_SPEED_PWM_CHANNEL_RESOLUTION,
    EEPROM_NAMESPACE_MOTOR_ARM,
    EEPROM_KEY_MOTOR_ARM_FIRST_GEAR_SPEED,
    EEPROM_KEY_MOTOR_ARM_SECOND_GEAR_SPEED,
    EEPROM_KEY_MOTOR_ARM_THIRD_GEAR_SPEED,
    EEPROM_KEY_MOTOR_ARM_DEFAULT_SPEED,
    EEPROM_KEY_MOTOR_ARM_ACTIVE_BREAKING);

static Motor __Motor_trolley(
    MOTOR_TROLLEY_NAME,
    MOTOR_TROLLEY_PIN_1_DIRECTION_CONTORLLING,
    MOTOR_TROLLEY_PIN_2_DIRECTION_CONTORLLING,
    MOTOR_TROLLEY_PIN_SPEED_CONTROLLING,
    MOTOR_TROLLEY_SPEED_PWM_CHANNEL_NUMBER,
    MOTOR_TROLLEY_SPEED_PWM_CHANNEL_FREQUENCY, 
    MOTOR_TROLLEY_SPEED_PWM_CHANNEL_RESOLUTION,
    EEPROM_NAMESPACE_MOTOR_TROLLEY,
    EEPROM_KEY_MOTOR_TROLLEY_FIRST_GEAR_SPEED,
    EEPROM_KEY_MOTOR_TROLLEY_SECOND_GEAR_SPEED,
    EEPROM_KEY_MOTOR_TROLLEY_THIRD_GEAR_SPEED,
    EEPROM_KEY_MOTOR_TROLLEY_DEFAULT_SPEED,
    EEPROM_KEY_MOTOR_TROLLEY_ACTIVE_BREAKING);

static Motor __Motor_coil(
    MOTOR_COIL_NAME,
    MOTOR_COIL_PIN_1_DIRECTION_CONTORLLING,
    MOTOR_COIL_PIN_2_DIRECTION_CONTORLLING,
    MOTOR_COIL_PIN_SPEED_CONTROLLING,
    MOTOR_COIL_SPEED_PWM_CHANNEL_NUMBER,
    MOTOR_COIL_SPEED_PWM_CHANNEL_FREQUENCY, 
    MOTOR_COIL_SPEED_PWM_CHANNEL_RESOLUTION,
    EEPROM_NAMESPACE_MOTOR_COIL,
    EEPROM_KEY_MOTOR_COIL_FIRST_GEAR_SPEED,
    EEPROM_KEY_MOTOR_COIL_SECOND_GEAR_SPEED,
    EEPROM_KEY_MOTOR_COIL_THIRD_GEAR_SPEED,
    EEPROM_KEY_MOTOR_COIL_DEFAULT_SPEED,
    EEPROM_KEY_MOTOR_COIL_ACTIVE_BREAKING);

Motor* motors[NUMBER_OF_MOTORS] = {
	&__Motor_arm,
	&__Motor_trolley,
	&__Motor_coil
};