#ifndef MOTORS_H
#define MOTORS_H

#include <Arduino.h>
#include <Motor.h>
#include <types.h>

#define NUMBER_OF_MOTORS (3)

#define MOTOR_ARM_NAME "MOTOR_ARM"
#define MOTOR_ARM_DIRECTION_CONTROLLING_PIN_1 (23)
#define MOTOR_ARM_DIRECTION_CONTROLLING_PIN_2 (22)
#define MOTOR_ARM_SPEED_CONTROLLING_PIN (21)

#define MOTOR_TROLLEY_NAME "MOTOR_TROLLEY"
#define MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_1 (19)
#define MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_2 (18)
#define MOTOR_TROLLEY_SPEED_CONTROLLING_PIN (17)

#define MOTOR_COIL_NAME "MOTOR_COIL"
#define MOTOR_COIL_DIRECTION_CONTROLLING_PIN_1 (16)
#define MOTOR_COIL_DIRECTION_CONTROLLING_PIN_2 (15)
#define MOTOR_COIL_SPEED_CONTROLLING_PIN (14)

// MotorId is defined in ComponentHandler/types.h

class Motor;

extern Motor* motors[NUMBER_OF_MOTORS];

#endif /* MOTORS_H */