#ifndef MOTORS_H
#define MOTORS_H

#include <Arduino.h>
#include <Motor.h>

#define NUMBER_OF_MOTORS (3)

#define MOTOR_ARM_NAME "MOTOR_ARM"
#define MOTOR_ARM_DIRECTION_CONTROLLING_PIN_1 (0)
#define MOTOR_ARM_DIRECTION_CONTROLLING_PIN_2 (0)
#define MOTOR_ARM_SPEED_CONTROLLING_PIN (0)

#define MOTOR_TROLLEY_NAME "MOTOR_TROLLEY"
#define MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_1 (0)
#define MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_2 (0)
#define MOTOR_TROLLEY_SPEED_CONTROLLING_PIN (0)

#define MOTOR_COIL_NAME "MOTOR_COIL"
#define MOTOR_COIL_DIRECTION_CONTROLLING_PIN_1 (0)
#define MOTOR_COIL_DIRECTION_CONTROLLING_PIN_2 (0)
#define MOTOR_COIL_SPEED_CONTROLLING_PIN (0)

typedef enum {
    MOTOR_ARM,
    MOTOR_TROLLEY,
    MOTOR_COIL
} Motors;

class Motor;

extern Motor* motors[NUMBER_OF_MOTORS];

#endif /* MOTORS_H */