#include <Motors.h>

static Motor __Motor_arm(
    "MOTORE_BRACCIO",
    MOTOR_ARM_DIRECTION_CONTROLLING_PIN_1,
    MOTOR_ARM_DIRECTION_CONTROLLING_PIN_2,
    MOTOR_ARM_SPEED_CONTROLLING_PIN,
    EEPROM_ADDRESS_MOTOR_ARM_FIRST_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_ARM_SECOND_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_ARM_THIRD_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_ARM_DEFAULT_SPEED);

static Motor __Motor_trolley(
    "MOTORE_CARRELLO",
    MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_1,
    MOTOR_TROLLEY_DIRECTION_CONTROLLING_PIN_2,
    MOTOR_TROLLEY_SPEED_CONTROLLING_PIN,
    EEPROM_ADDRESS_MOTOR_TROLLEY_FIRST_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_TROLLEY_SECOND_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_TROLLEY_THIRD_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_TROLLEY_DEFAULT_SPEED);

static Motor __Motor_coil(
    "MOTORE_BOBINA",
    MOTOR_COIL_DIRECTION_CONTROLLING_PIN_1,
    MOTOR_COIL_DIRECTION_CONTROLLING_PIN_2,
    MOTOR_COIL_SPEED_CONTROLLING_PIN,
    EEPROM_ADDRESS_MOTOR_COIL_FIRST_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_COIL_SECOND_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_COIL_THIRD_GEAR_SPEED,
    EEPROM_ADDRESS_MOTOR_COIL_DEFAULT_SPEED);

Motor motors[NUMBER_OF_MOTORS] = {
	__Motor_arm,
	__Motor_trolley,
	__Motor_coil
};